### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mananapr** [mananapr/akari#1]
- [x] Add database support
- [x] Refactoring
- [x] Add Basic GUI
- [x] Add context menus for images
- [x] Add a working filter button, based on selected tags
- [x] Add ability to edit tags
- [x] Add a basic image viewer (full screen, slideshow)
- [x] Add comments and do some cleaning up
- [ ] Add option to rename files with tags

**Comment by suiqa** [comment]
Hello, I need "Add option to rename files with tags" function
